# about me

Lecturer in Psychophysiology and Cognitive Neuroscience<br>School of Psychology and Sport Science, Bangor University, UK

I am a researcher. I am broadly interested in the areas of psychophysiology, cognitive neuroscience, and biomedical engineering.

In my research, I use and develop methods of computational psycho/electrophysiology to study the modulatory effect of cognitive processes (e.g., motor control, working memory, perception), psychological states (e.g., mental fatigue), and disease (e.g, essential hypertension) on biological systems (e.g., cortical, cardiovascular, ocular, somatic) and their interplay (e.g., cross-frequency cross-system coupling).  

My background is in Psychology. In 2007 I received a BSc in Psychological, Cognitive, and Psychobiological Sciences from the University of Padova (Italy) followed in 2009 by an MSc in Experimental Psychology and Cognitive-Behavioural Neuroscience. It was during these years that I developed my passion for psychophysiology. After completing my MSc degree, I continued working as a research assistant at the Department of General Psychology, University of Padova, and then at the School of Sport and Exercise Sciences, University of Birmingham (UK). I then returned to Italy to sit the State Examination for Psychology, which is necessary for the professional practice in psychology. While continuing my personal study in psychophysiology, I decided to formally study Sport and Exercise Sciences and in 2013 I completed a double MSc awarded jointly by Lund University (Sweden) and the University of Leipzig (Germany). In 2014-15 I worked as a research assistant at the Centre for Cognitive Neuroscience, University of Salzburg (Austria), deepening my study of electrophysiological signal processing. I returned to the UK in 2015 to start an ESRC-funded PhD in Psychophysiology at the University of Birmingham while at the same time completing a PGCert in Advanced Research Methods and Skills. As part of my doctoral training, I had the opportunity to visit the Cognitive Motor Neuroscience Laboratory of the University of Maryland. In 2018 I started a 2-year postdoctoral fellowship at the School of Sport, Exercise, and Health Sciences, Loughborough University. Since 2020 I have been a Lecturer at the School of Psychology and Sport Science, Bangor University, where I am a member of the research institutes for the Psychology of Elite Performance (IPEP) and for Applied Human Physiology (IAHP).